### PR TITLE
Math correction

### PR DESCRIPTION
**Pull request by t-pollington**
Hi @edbaskerville and @kgostic,

Thanks for putting this code together. I like your minimal code style Ed. Submitting a pull request consisting of:

 * correction to reduced/normalised chi-square statistic. Previously it had used _1/N_ whereas _1/(N-2)_ is required.

* while I was in there checking the code I was annoyingly changing things like naming etc. Please feel free to ignore that :)

As updated in the `.Rmd` I think the `sample(..., replace = TRUE)` initial condition trial is a bit extreme and RL does need something that looks like an epidemic curve in the observed curve to be able to start. If you were thinking of creating a DoI for this code I'd be interested as I might like to cite this resource later.

Kind regards, Tim.

### CODE REVIEW

**Comment by edbaskerville** [comment]
Thanks for the suggestion, and sorry for the delay—I haven't been working on this stuff for the last several months.

Perhaps you could explain the chi-squared statistic change? I don't know anything deep about chi-squared tests; I was just blindly implementing from the source ([Goldstein et al. 2009](https://doi.org/10.1073/pnas.0902958106)).

**Comment by edbaskerville** [comment]
Ah, I see your commit message. Conceptually, it's an adjustment to compensate for overfitting, I guess?

**Comment by t-pollington** [comment]
> Ah, I see your commit message. Conceptually, it's an adjustment to compensate for overfitting, I guess?

Hi @edbaskerville just returned from hols. Yes that's my understanding of it, both underfitting, and overfitting if you iterate too far. The only error I could find was the degrees of freedom used in the denominator, however as I've said I doubt that makes much difference to the result so in all intents and purposes it's a good representation of the algorithm in code.

**Review by kgostic — APPROVED** [review]
Accpeting TP's pull request. Minor changes to notes and text, and a correction to the chi-squared stopping criterion.

**Pull request merged**
